######################################################################
#
# File name : main_compile.do
# Created on: Wed Jan 03 12:24:25 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib work
vlib msim

vlib msim/xil_defaultlib
vlib msim/xpm
vlib msim/blk_mem_gen_v8_3_3

vmap xil_defaultlib msim/xil_defaultlib
vmap xpm msim/xpm
vmap blk_mem_gen_v8_3_3 msim/blk_mem_gen_v8_3_3

vlog -64 -incr -sv -work xil_defaultlib  \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_base.sv" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_dpdistram.sv" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_dprom.sv" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_sdpram.sv" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_spram.sv" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_sprom.sv" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_tdpram.sv" \

vcom -64 -93 -work xpm  \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -64 -incr -work blk_mem_gen_v8_3_3  \
"../../../vga_game_cnm.ip_user_files/ipstatic/blk_mem_gen_v8_3_3/simulation/blk_mem_gen_v8_3.v" \

vlog -64 -incr -work xil_defaultlib  \
"../../../vga_game_cnm.srcs/sources_1/ip/rock_pic/sim/rock_pic.v" \
"../../../vga_game_cnm.srcs/sources_1/ip/boom_up/sim/boom_up.v" \
"../../../vga_game_cnm.srcs/sources_1/ip/boom_right/sim/boom_right.v" \
"../../../vga_game_cnm.srcs/sources_1/ip/boom_left/sim/boom_left.v" \
"../../../vga_game_cnm.srcs/sources_1/ip/boom_down/sim/boom_down.v" \
"../../../vga_game_cnm.srcs/sources_1/ip/boat_up/sim/boat_up.v" \
"../../../vga_game_cnm.srcs/sources_1/ip/boat_right/sim/boat_right.v" \
"../../../vga_game_cnm.srcs/sources_1/ip/boat_left/sim/boat_left.v" \
"../../../vga_game_cnm.srcs/sources_1/ip/boat_down/sim/boat_down.v" \
"../../../vga_game_cnm.srcs/sources_1/ip/blk_mem_gen_0_1/sim/blk_mem_gen_0.v" \
"../../../vga_game_cnm.srcs/sources_1/new/seg.v" \
"../../../vga_game_cnm.srcs/sources_1/new/ps2.v" \
"../../../vga_game_cnm.srcs/sources_1/new/game_main.v" \
"../../../vga_game_cnm.srcs/sources_1/new/main.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

