# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/boom_left/boom_left.xci
# IP: The module: 'boom_left' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/boom_left/boom_left_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'boom_left'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/boom_left/boom_left.xci
# IP: The module: 'boom_left' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/boom_left/boom_left_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'boom_left'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
