# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/boat_down/boat_down.xci
# IP: The module: 'boat_down' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/boat_down/boat_down_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'boat_down'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/boat_down/boat_down.xci
# IP: The module: 'boat_down' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/boat_down/boat_down_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'boat_down'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
