# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.cache/wt [current_project]
set_property parent.project_path C:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files C:/Users/youyaoyin/Pictures/game/sea.coe
add_files C:/Users/youyaoyin/Pictures/game/rock.coe
add_files C:/Users/youyaoyin/Pictures/game/boat_right.coe
add_files C:/Users/youyaoyin/Pictures/game/boatup.coe
add_files C:/Users/youyaoyin/Pictures/game/boatleft.coe
add_files C:/Users/youyaoyin/Pictures/game/boat_down.coe
add_files C:/Users/youyaoyin/Pictures/game/boomdown.coe
add_files C:/Users/youyaoyin/Pictures/game/boomleft.coe
add_files C:/Users/youyaoyin/Pictures/game/boomright.coe
add_files C:/Users/youyaoyin/Pictures/game/boomup.coe
add_files -quiet c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0.dcp]
add_files -quiet c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/rock_pic/rock_pic.dcp
set_property used_in_implementation false [get_files c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/rock_pic/rock_pic.dcp]
add_files -quiet c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/boat_right/boat_right.dcp
set_property used_in_implementation false [get_files c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/boat_right/boat_right.dcp]
add_files -quiet c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/boat_up/boat_up.dcp
set_property used_in_implementation false [get_files c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/boat_up/boat_up.dcp]
add_files -quiet c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/boat_left/boat_left.dcp
set_property used_in_implementation false [get_files c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/boat_left/boat_left.dcp]
add_files -quiet c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/boat_down/boat_down.dcp
set_property used_in_implementation false [get_files c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/boat_down/boat_down.dcp]
add_files -quiet c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/boom_down/boom_down.dcp
set_property used_in_implementation false [get_files c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/boom_down/boom_down.dcp]
add_files -quiet c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/boom_up/boom_up.dcp
set_property used_in_implementation false [get_files c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/boom_up/boom_up.dcp]
add_files -quiet c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/boom_left/boom_left.dcp
set_property used_in_implementation false [get_files c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/boom_left/boom_left.dcp]
add_files -quiet c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/boom_right/boom_right.dcp
set_property used_in_implementation false [get_files c:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/ip/boom_right/boom_right.dcp]
read_verilog -library xil_defaultlib C:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/sources_1/new/game_main.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/constrs_1/new/vga.xdc
set_property used_in_implementation false [get_files C:/Users/youyaoyin/vga_game_cnm/vga_game_cnm.srcs/constrs_1/new/vga.xdc]


synth_design -top game_main -part xc7a100tcsg324-3


write_checkpoint -force -noxdef game_main.dcp

catch { report_utilization -file game_main_utilization_synth.rpt -pb game_main_utilization_synth.pb }
